# Generated by Django 5.0.3 on 2024-04-29 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=150)),
                ('animal', models.CharField(choices=[('cat', 'Cat'), ('dog', 'Dog')], max_length=3)),
                ('common_signs', models.TextField(default='this is the most common signs')),
                ('hurt_degree', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('moderately_severe', 'Moderately_severe'), ('severe', 'Severe'), ('critical', 'Critical')], max_length=50)),
                ('treatment', models.TextField(default='These are the treatments we recommend')),
            ],
        ),
    ]
